// dccstatusline — MIT
// buildnum: increment the persistent build counter and generate version.h

#include <errno.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint64_t counter_read(const char *);
static bool counter_write(const char *, uint64_t);
static bool header_write(const char *, const char *, uint64_t);
static bool fail(const char *);

// A missing or unreadable counter file is not an error: the counter simply
// restarts, and the next write heals it.
static uint64_t
counter_read(const char *path)
{
  uint64_t n = 0;
  FILE *f = fopen(path, "r");

  if(f)
  {
    char buf[32];

    if(fgets(buf, sizeof buf, f))
    {
      char *end = NULL;
      unsigned long long v = strtoull(buf, &end, 10);

      if(end != buf && errno != ERANGE) n = (uint64_t)v;
    }

    fclose(f);
  }

  return(n);
}

static bool
counter_write(const char *path, uint64_t n)
{
  FILE *f = fopen(path, "w");

  if(!f) return(fail(path));

  if(fprintf(f, "%" PRIu64 "\n", n) < 0 || fclose(f) != 0) return(fail(path));

  return(true);
}

static bool
header_write(const char *path, const char *version, uint64_t n)
{
  FILE *f = fopen(path, "w");

  if(!f) return(fail(path));

  if(fprintf(f,
             "// generated by buildnum — do not edit\n"
             "#define DCC_VERSION \"%s\"\n"
             "#define DCC_BUILD %" PRIu64 "\n"
             "#define DCC_BUILD_STRING \"dccstatusline v%s (build #%" PRIu64 ")\"\n",
             version, n, version, n) < 0 || fclose(f) != 0)
    return(fail(path));

  return(true);
}

static bool
fail(const char *path)
{
  fprintf(stderr, "buildnum: %s: %s\n", path, strerror(errno));

  return(false);
}

int
main(int argc, char **argv)
{
  uint64_t n;

  if(argc != 4)
  {
    fprintf(stderr, "usage: %s <version.h-out> <counter-file> <version>\n", argv[0]);
    return(EXIT_FAILURE);
  }

  errno = 0;
  n = counter_read(argv[2]) + 1;

  if(!counter_write(argv[2], n) || !header_write(argv[1], argv[3], n))
    return(EXIT_FAILURE);

  return(EXIT_SUCCESS);
}
